#!/bin/bash
DP=$(dirname $0)
BUILD_SLEEP=30
NAME=zcs-dev
TAG=8.8.1
REPO=zimbra/zcs-dev
REPO_BASE="${REPO}-base"
IMAGE="${REPO}:${TAG}"
IMAGE_BASE="${REPO_BASE}:${TAG}"

function wait_build {
    DONE=no
    while [ "${DONE}" == "no" ]
    do
        echo "$(date) - Waiting for build to complete..."
        sleep ${BUILD_SLEEP}
        docker logs zcs-dev | grep -q 'SETUP COMPLETE'
        if [ $? -eq 0 ]
        then
            echo "$(date) - Build has finished..."
            DONE=yes
        fi
    done
}

echo "$(date) - Creating intermediate build image ${IMAGE_BASE}..."
docker-compose -f "${DP}/docker-compose-base.yml" up -d
wait_build

echo "$(date) - Pausing containers..."
docker-compose -f "${DP}/docker-compose-base.yml" pause
echo "$(date) - Creating image ${IMAGE} from paused container ${NAME}..."
docker export ${NAME} | docker import - ${IMAGE}
echo "$(date) - Shutting build containers down..."
docker-compose -f "${DP}/docker-compose-base.yml" down
echo "$(date) - Removing intermediate build image ${IMAGE_BASE}"
docker rmi ${IMAGE_BASE}
echo "$(date) - Docker image ${IMAGE} is ready. Run with 'docker-compose up -d'"

