#!/bin/bash
# Spin-up and initialize a container based on this image:
#    gordy/zcs-ubuntu-1604:8.8.1-zcs-base
# Assumes the presence of a user-defined network called "zcs".  Create it as follows:
#   docker network create --driver bridge zcs
# NOTES: 
# 1. The bridge driver assumes that all containers that use it are running
#    from the same host.
# 2. Note the host->container port mappings.  Feel free to tweak this as
#    desired.
# 3. Note the host folders that are mapped into the container.
#    The slash-zimbra -> /zimbra mapping is used by the init script
#    The home-zimbra -> /home/zimbra mapping is intended to be 
#    used as a place to keep all of your git repos and other persistent
#    preserved the next time you run the container.  You can instead
#    map some other folder on your host to /home/zimbra.  You need
#    to provide an absolute path to the host folder. The "/home/zimbra"
#    thing is a convention that the internal server team uses.

pushd $(dirname $0)
ABS=$(pwd)
popd

docker run --network zcs \
  --hostname zcs-dev.test \
  -p 2222:22 -p 8143:143 -p 8443:443 -p 8993:993 -p 9998:9998 -p 9999:9999 \
  -v ${ABS}/slash-zimbra:/zimbra \
  -v ${ABS}/home-zimbra:/home/zimbra \
  --name=zcs-dev \
  -it gordy/zcs-ubuntu-1604:8.8.1-zcs-base \
  /zimbra/init
