#!/bin/bash
# Do this after a ZCS install to fix necessary permissions
# Expects the following environment variables to be set. These are used to
# update the information in the .gitconfig file that is laid down.
# * GITEMAIL - The email address you use on github
# * GITNAME - Your first and last name.

DN=$(dirname $0)
chown zimbra:zimbra /opt/zimbra/.
chown zimbra:zimbra /opt/zimbra/.*
chmod -R o+w /opt/zimbra/lib/
chmod -R o+w /opt/zimbra/jetty/
chmod -R o+w /opt/zimbra/common/etc/openldap/schema
chmod o+w /opt/zimbra/conf/zimbra.ldif
chmod +w /opt/zimbra/conf/attrs/zimbra-attrs.xml
chmod -R o+w /opt/zimbra/common/etc/openldap/zimbra
cp ${DN}/junit-4.8.2.jar  /opt/zimbra/jetty/webapps/service/WEB-INF/lib/.
echo "zimbra:zimbra" | chpasswd

OZ=${DN}/opt-zimbra
for f in $(ls ${OZ})
do
    F=${OZ}/${f}
    if [ "$f" = "DOT-ssh" ]
    then
        cp ${F}/* /opt/zimbra/.ssh
        chown zimbra /opt/zimbra/.ssh/*
    fi

    if [ -f "${F}" ]
    then
        F2=".$(echo ${f} | tr -d 'DOT-')"
        cp "${F}" "/opt/zimbra/${F2}"
        chown zimbra "/opt/zimbra/${F2}"
    fi
done

sed -i.bak "s/GITEMAIL/${GITEMAIL}/" /opt/zimbra/.gitconfig
sed -i.bak "s/GITNAME/${GITNAME}/" /opt/zimbra/.gitconfig
